### ISSUE TITLE
Extention cannot work with non-latin UTF-8-codepage symbols in path

### ISSUE THREAD

**Issue by Nick222** [rkokkelk/todo.txt-ext#28] opened 2017-03-12 18:39 UTC
Xubuntu 16.10
Thunderbird 45.7.0
Todo.txt Extension 0.8.4
Extention cannot work with non-latin UTF-8-codepage symbols in path to file todo.txt

I see in prefs.js (in Thunderbird profile folder):

user_pref("extensions.todotxt.todo-txt", "/home/nick/A_/4@>/2) 018=5B 8 :><?LNB5@/ 01>G0O/Thunderbird/ToDo_txt/todo.txt");

instead right path.

After Thunderbird start it opened window: "Cannot find file todo.txt" - and Thunderbird freeze...

**Comment by rkokkelk** [comment] 2017-04-17 10:32
Hi,

My apologies for my late reply but I have been very busy lately. This is indeed a bug, however something similar was already reported a couple of months ago, see #11. This resulted in a bug being reported to Thunderbird: [https://bugzilla.mozilla.org/show_bug.cgi?id=1284166](https://bugzilla.mozilla.org/show_bug.cgi?id=1284166). 

So could you verify that your bug is fixed in the most recent Thunderbird version? Thank you for reporting this issue!

**Comment by Nick222** [comment] 2017-04-17 10:59
I cannot verify it - after install this add-on and restart Thunderbird cannot work (freeze).
Xubuntu 17.04 Thunderbird 45.8.0

**Comment by rkokkelk** [comment] 2017-04-17 16:18
Okay, that is strange. I'll try to verify it using Thunderbrid `45.8.0`. But as mentioned in the previous issue, the issues with non-latin characters in the file path should be resolved with Thunderbird `46+`. 

Could you verify that your issue is resolved when you use Thunderbird version `46` or higher?

**Comment by Nick222** [comment] 2017-04-17 16:27
I cannot install version 46 now, excuse me. It is not in official Xubuntu PPA and I do not know any other PPA with newer version.

**Comment by rkokkelk** [comment] 2017-04-17 16:42
Okay, could you specify which path you have used with the non-latin characters. I'll try it on the most recent Thunderbird version and verify if the issue still persists.

**Comment by Nick222** [comment] 2017-04-18 22:02
I install Thunderbird 53.0b2 (64)
After install this add-on and restart Thunderbird I see window with name "Warning todo.txt" and with text "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getComplexValue]"

**Comment by rkokkelk** [comment] 2017-04-19 05:17
Okay, it should definitely been fixed in that version of Thunderbird. Could you specify the path that you are using for both your todo.txt and done.txt with the non-latin special characters.

Then I can verify it and hopefully fix this issue.

**Comment by Nick222** [comment] 2017-04-19 07:05
I erase all about Todo.txt in Thunderbird`s options and cannot write new path because Thunderbird freeze after restart.
Can You write - what option in option`s file are created by Todo.txt ?

**Comment by rkokkelk** [comment] 2017-04-19 14:29
Okay it is strange that TB still freezes even though you have removed the add-on. Currently the 

```

**Comment by Nick222** [comment] 2017-04-19 15:05
No - Thunderbird freezes only when I install add-on. After delete add-on`s file and erase it`s options from Thunderbird everything is OK.
Path "~/Рабочая/Thunderbird/ToDo_txt/"

**Comment by rkokkelk** [comment] 2018-08-27 08:46
Sorry for the very late reply, but I've just tried the exact path you have specified on Arch Linux with Thunderbird version `52.9.1` and I cannot reproduce your issue.

With the exact path you have specified, I do not encounter any issues and Thunderbird keeps working as expected. Therefore I'm closing this issue, if you can still reproduce this issue with an up to date version of TB, please feel free to reopen this issue.

**Closed by rkokkelk** 2018-08-27 08:46 UTC
Labels: bug
