### ISSUE TITLE
Empty task list

### ISSUE THREAD

**Issue by MartyLake** [rkokkelk/todo.txt-ext#15] opened 2016-12-05 08:02 UTC
Hi !

After configuring the paths, the todo list stays empty in Thunderbird. When I create a task, I can see it briefly in the task list (5 seconds) and then it disappears. When I "cat" the todo.txt file, everything is ok, I can even see the added task.

Can you help me with this? :)
Best,

**Comment by rkokkelk** [comment] 2016-12-06 18:18
Hi,

Okay that is strange. could you supply your todo.txt or something similar so that I can test it. Thank you for your bug.

**Comment by MartyLake** [comment] 2016-12-07 07:16
Sure !

[done.txt](https://github.com/rkokkelk/todo.txt-ext/files/635886/done.txt)
[todo.txt](https://github.com/rkokkelk/todo.txt-ext/files/635887/todo.txt)

![capture du 2016-12-07 08-15-42](https://cloud.githubusercontent.com/assets/1246794/20958348/7a8d0026-bc55-11e6-9e94-568c1990ea1d.png)
![capture du 2016-12-07 08-16-12](https://cloud.githubusercontent.com/assets/1246794/20958349/7a8c897a-bc55-11e6-81dc-4db7d8269ef7.png)

**Comment by rkokkelk** [comment] 2016-12-09 23:09
Hi, 

small status update, there have been some discrepancies in the format with your todo.txt file. The JavaScript parser that I use generates errors which are not properly handled within my add-on thus causing nothing to show in Thunderbird.

So far, I have not found where the syntax error are located exactly but I'll work on that.  Once I found the error I'll contact you, then I'll also be working on the JS parser in order to properly handle this kinds of format errors in the future. 

I'll keep you poster on the progress.

**Comment by MartyLake** [comment] 2016-12-10 07:41
Thanks for the update! I'm sad to hear that my todotxt has errors as I'm
only using applications to access it.

Best,

Le 10 déc. 2016 00:09, "Roy Kokkelkoren" <notifications@github.com> a
écrit :

**Comment by rkokkelk** [comment] 2016-12-19 23:07
Hi,

I think the issue could also be possible related to the Thunderbird version. Using your todo.txt files and using Thunderbird 45.5.1  with the latest version of the add-on results in the todo's being showed as it should. 

So could you specify which version of Thunderbird you are using so that I can verify the bug. Thank you.

**Comment by rkokkelk** [comment] 2017-01-10 18:54
So unfortunately the previously reported bug was related to some developed code in my branch, which when cleaned, a.k.a. running the code from the Mozilla repo, results in the tasks being shown correctly. 

So I'm unable to reproduce your issue, I've tested it on Ubuntu 16.04 with Thunderbird `45.5.1` and on Arch with Thunderbird `45.6.0`. Both has shown the add-on working correctly. 

So I'm closing this issue, if you could specify some more information your are more than welcome to reopen the issue.

**Closed by rkokkelk** 2017-01-10 18:54 UTC
Labels: bug

**Comment by MartyLake** [comment] 2017-01-11 12:57
Hi !

Ow, ok :(
I'll probably move to taskwarrior anyway. Thanks for your time,

best,


---
Matthieu TALBOT
neogaldr@gmail.com

+33 629 22 15 70
fr.linkedin.com/in/matthieutalbot
http://www.soundcloud.com/Marty-Lake
http://lifehacker.com/5028808/how-eom-makes-your-email-more-efficient
