### ISSUE TITLE
Wrong date written to done.txt

### ISSUE THREAD

**Issue by JoergPalmer** [rkokkelk/todo.txt-ext#22] opened 2017-02-02 22:36 UTC
When flagging a task as done it is added to the done.txt file, which is correct. The "done date" is written in a wrong way though.

It should be like:
`x <Priority> <completion date> <*creation date*> <description> ....
`

But in fact it is like:
`x <Priority> <completion date> <*completion date*> <description> ....
`

My version information:
TB v45.4.0 (Linux), todo.txt extension v0.8.1

**Comment by rkokkelk** [comment] 2017-02-03 09:32
Hi,

Thank you for reporting this issue. Unfortunately I cannot reproduce the problem. When I complete a task I get the following format:

`x <completion date> <Priority> <creation date (If used)> <description>`

Which is as it should be. I've tried with multiple configurations. Could you provide me with an example todo.txt file and your current settings so that I can further verify your issues? Thank you for your help.

```
x 2017-02-03 (A) 2017-02-01 foobar 9875
x 2016-07-29 (A) 2016-07-04 foobar123 due:2016-08-25
x 2016-07-29 (A) 2016-07-21 test test @PR +Anniversary +Birthday +TTT
x 2016-07-19 (B) 2016-07-19 test 1234
x 2016-07-19 (C) 2016-07-19 foobar due:2016-02-27 @Project +Foobar
x 2017-02-03 (A) 2017-02-01 foobar 5%
```

**Comment by JoergPalmer** [comment] 2017-02-03 10:41
Absolutely! Here is the content of a sample todo.txt file:

> (A) 2017-01-03 This is just test task number 1 @Computer
> (B) 2017-01-04 This is just test task number 2 @Home
> (B) 2017-01-05 This is just test task numer 3 @Work
> (B) 2017-01-06 This is just test task number 4 @Home
> (B) 2017-01-07 This is just test task numer 5 @Work
> (A) 2017-01-08 This is just test task number 6 @Computer
> (B) 2017-01-09 This is just test task numer 7 @Work
> (A) 2017-01-10 This is just test task number 8 @Computer
> (B) 2017-01-11 This is just test task number 9 @Home


Ticking off some of them results in this done.txt file:

> x 2017-02-03 (B) 2017-02-03 This is just test task number 5 @Work
> x 2017-02-03 (B) 2017-02-03 This is just test task numer 9 @Home
> x 2017-02-03 (A) 2017-02-03 This is just test task number 1 @Computer

As for the settings, the file names are set properly, and here are the other selections:

- Use Thunderbird functionality: ON
- Use todo creation time stamp: ON
- Show projects and context in title: OFF

My version information:
TB v45.7.0 (Linux), todo.txt extension v0.8.1

**Comment by rkokkelk** [comment] 2017-02-03 12:06
My apologies I was testing it on a slightly newer branch which already contained a fix. So I've confirmed the issue and have created a fix. Will soon be released under version `0.8.2`. Once pushed to the Mozilla repository I will close this issue.

**Comment by rkokkelk** [comment] 2017-02-03 13:10
Version `0.8.2` has been uploaded to the Mozilla repository and is currently under review. Version should be available within the next couple of days.

**Closed by rkokkelk** 2017-02-03 13:10 UTC
Labels: bug

**Comment by JoergPalmer** [comment] 2017-02-03 13:27
Confirmed to be working correctly ... Thank you!
