### ISSUE TITLE
Not showing clear messages towards users while handling exceptions

### ISSUE THREAD

**Issue by firmgently** [rkokkelk/todo.txt-ext#13] opened 2016-08-09 13:22 UTC
Thanks for the fix. The following behaviour is still the same in 0.7.1.

I have a showstopper which I wouldn't call a bug as it's my own 'fault' for having a weird setup. I'll give you the info anyway just in case it's useful to you (or if it's an easy fix, even better as I'd love to be able to use this addon).

I keep a folder from a remote server permanently mounted via SSHFS. So if my remotely mounted dir is TODODIR I end up with something like:

/home/myname/TODODIR/todo.txt
/home/myname/TODODIR/done.txt

I initially had permissions problems but seem to have fixed them and since then every programme I've used to read/write to this folder works fine (although there is sometimes a delay of anything up to a few seconds).

todo.txt-ext will allow me to browse to and select those files and lists the paths correctly in preferences. It will show me existing items from those todo files in my calendar. **But** if I try to create a new task or do any form of writing to the files I get:

An error occurred when writing to the calendar Todo.txt!

Details...
Error code: MODIFICATION_FAILED
Description:

(ie. blank description).

Anyway I'm not trying to complain, you didn't advertise the add-on as working with SSHFS, I just tried it and it doesn't work so I thought I'd pass the info along. Thanks for all your hard work anyway! :)

**Comment by rkokkelk** [comment] 2016-08-09 13:35
Hi, 

Thanks again for the feedback. I'm using the Mozilla API for all interactions with the filesystem so it could be that there is an error within the specific API. But it is very strange that reading works but not writing. I'll try a new implementation tonight and see if I can reproduce the error.

**Comment by firmgently** [comment] 2016-08-09 13:51
Hi yeah I had a quick look  at the code and noticed you were using the API (as is recommended I'm sure). I wondered if it didn't wait long enough for confirmation that the write had succeeded (I don't even know if that makes sense!) but then if that's how the API is written it's out of your control I guess.

Thanks for your efforts anyway but if it's only me with the problem I don't expect you to spend too much time on it (although it's very good of you).

If there's anything I can do to help please let me know!

**Comment by rkokkelk** [comment] 2016-08-09 19:40
Oke, I've tried the same implementation and it works fine with me. I can both read and add new todo's, modify and delete them. It all appears correctly on the hosting machine. So I think there might be something wrong with your setup. 

I've tried it on Thunderbird `45.2.0` & Icedove `38.8.0` and I've used the following SSHFS versions:

```
SSHFS version 2.8
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```
So if you can specify more precisely where the issue resides I'll look into it again but until then I will close this issue. But you more than welcome to provide more information or code if you desire. Thanks again for your feedback.

**Comment by firmgently** [comment] 2016-08-10 12:44
I don't know what else to change either. I've tried recreating new empty todo files, using different methods of sshfs (fstab and now autofs), uninstalling/reinstalling the addon. Pluma, Atom, todo.txt-cli can all read/write no problem.

I've got:
SSHFS version 2.5
FUSE library version: 2.9.3
fusermount version: 2.9.3
using FUSE kernel interface version 7.19

I was on Icedove 38.7.0, just updated to 45.1.0 - still get the same error when I try to write.

As you say maybe there's something wrong with my setup but I wouldn't know what else to look at. I give up! I've spent days messing around trying to make my to-do list work instead of doing stuff on my to-do list :)

THANK YOU though, as you obviously took time trying to replicate my problem - much appreciated. If I ever find out what the problem was I'll update here.

**Comment by rkokkelk** [comment] 2016-08-10 12:52
There is still something you can try to determine what the issue is. You can install the add-on manually with debugging enabled to verify what the errors are. Use the following steps to do this.

1 `git clone https://github.com/rkokkelk/todo.txt-ext.git`
2 `./build.sh -d`
3 Load `todotxt_0.7.1.xpi` into Thunderbird 
  - Thunderbird add-on tab, gear next to search bar, Install add-on from file

4 Use error console to see messages `Ctrl-Shift-j`.

This will show many messages related to the functionality of the add-on, if you can post any messages related to the error I can continue from there.

**Comment by firmgently** [comment] 2016-08-10 13:49
Great suggestion thanks - I might take a couple of days to get around to it but will do so and report back!

**Comment by firmgently** [comment] 2016-08-10 15:17
Ok curiosity got the better of me. I wish it hadn't - I might have postponed my embarrassment. User Error :(

As soon as I read the warning/error I realised as I guess you will that I was making a stupid mistake.


Timestamp: 10/08/16 16:12:25
Warning: There has been an error reading data for calendar: Todo.txt.  However, this error is believed to be minor, so the program will attempt to continue. Error code: 0x8000ffff. Description: This calendar only accepts todos.
Source File: file:///home/person/.icedove/reaa4ssaqs.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 962

Timestamp: 10/08/16 16:12:25
Error: An error occurred when writing to the calendar Todo.txt! Error code: MODIFICATION_FAILED. Description: 
Source File: resource://calendar/modules/calUtils.jsm -> file:///home/person/.icedove/reaa4ssaqs.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 959

Yep I was trying to create an **event** not a **task** (I was double-clicking a day in the calendar, my preferred method of adding events/tasks).

I'm so sorry for wasting your time.

Even though I fully admit the silliness was mine, might I humbly suggest in a future version giving the user some feedback if they make the same mistake as I did?

Thanks for the add-on and your excellent help!

**Comment by rkokkelk** [comment] 2016-08-10 18:30
Ah, yeah that does not work because events are different types of objects which does not work with todo.txt. But as you can see that I create an appropriate exception with a correct error message but I agree that it is not correctly displayed towards the users.

I'll work on this improvement, but good to know that the add-on works with SSHFS.

**Comment by firmgently** [comment] 2016-08-10 18:38
Yeah exactly, the existing "This calendar only accepts todos." should do the trick if it makes it across to the user :)

I've only recently started using todo.txt and I'll be using it in the terminal sometimes and eventually on Android, so I have to sort out my own workflow. But yes the add-on seems to work nicely with SSHFS. Good work!

**Comment by rkokkelk** [comment] 2017-01-11 06:09
Currently under review by Mozilla, but the next version 0.8 will include improved error information. Any errors will be shown in a small popup containing a simple message in the locale of the user. 

The addon will be probably be published in the next couple of days. So I'm closing this issue. If the current fix is not sufficient please feel free to reopen this issue.

**Closed** 2017-01-11 06:09 UTC
Labels: bug, enhancement
